apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-app 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calculator-app
  template:
    metadata:
      labels:
        app: calculator-app
    spec:
      containers:
      - name: calculator-app-container
        image: stevymonkam/calculator-prod:115-unstable
        ports:
        - containerPort: 901

